version: '3'

services:
  jupyter:
    image: jupyter/datascience-notebook
    volumes:
      - /tmp/jupyter/notebooks:/home/notebooks
    ports:
      - 8888:8888
    container_name: jupyter-container
